CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'Atimbag@2023';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS `ringier_classified` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
